apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: titanic-prediction-alerts
  namespace: monitoring
  labels:
    app: titanic-prediction
    prometheus: kube-prometheus
spec:
  groups:
  - name: titanic.rules
    rules:
    # API Health Rules
    - alert: HighLatency
      expr: rate(titanic_api_request_latency_seconds_sum{endpoint="/api/v1/predict"}[5m]) / rate(titanic_api_request_latency_seconds_count{endpoint="/api/v1/predict"}[5m]) > 0.5
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: High API latency detected
        description: API latency is above 500ms for the last 5 minutes

    - alert: HighErrorRate
      expr: rate(titanic_api_requests_total{status_code=~"5.*"}[5m]) / rate(titanic_api_requests_total[5m]) > 0.05
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: High error rate detected
        description: Error rate is above 5% for the last 5 minutes

    # Model Health Rules
    - alert: FeatureDrift
      expr: feature_drift > 0.3
      for: 15m
      labels:
        severity: warning
      annotations:
        summary: Feature drift detected
        description: Feature drift score is above threshold for {{ $labels.feature_name }}

    - alert: FeatureStoreUnhealthy
      expr: feature_store_health == 0
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: Feature store component unhealthy
        description: Feature store component {{ $labels.component }} is reporting unhealthy status

    - alert: HighModelLatency
      expr: rate(titanic_model_prediction_latency_seconds_sum[5m]) / rate(titanic_model_prediction_latency_seconds_count[5m]) > 0.1
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: High model prediction latency
        description: Model prediction latency is above 100ms for version {{ $labels.model_version }}

    # System Health Rules
    - alert: HighMemoryUsage
      expr: titanic_system_memory_usage_bytes > 500000000
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: High memory usage
        description: Application memory usage is above 500MB 