apiVersion: batch/v1
kind: Job
metadata:
  name: find-model
  namespace: titanic-prediction
spec:
  template:
    spec:
      containers:
      - name: find-model
        image: titanic-prediction:latest
        imagePullPolicy: Never
        command: ["sh", "-c", "find /app/models -name titanic_model.joblib"]
        volumeMounts:
        - name: model-volume
          mountPath: /app/models
      restartPolicy: Never
      volumes:
      - name: model-volume
        persistentVolumeClaim:
          claimName: titanic-models-pvc
