apiVersion: batch/v1
kind: Job
metadata:
  name: check-data
  namespace: titanic-prediction
spec:
  template:
    spec:
      containers:
      - name: check-data
        image: titanic-prediction:latest
        imagePullPolicy: Never
        command: ["sh", "-c", "ls -la /app/models/..data/"]
        volumeMounts:
        - name: model-volume
          mountPath: /app/models
      restartPolicy: Never
      volumes:
      - name: model-volume
        persistentVolumeClaim:
          claimName: titanic-models-pvc
