apiVersion: batch/v1
kind: Job
metadata:
  name: list-runs
  namespace: titanic-prediction
spec:
  template:
    spec:
      containers:
      - name: list-runs
        image: titanic-prediction:latest
        imagePullPolicy: Never
        command: ["python", "-c", "import mlflow; mlflow.set_tracking_uri(\"file:///app/models/mlruns\"); print(\"Available runs:\"); [print(f\"Run ID: {run.info.run_id}\") for run in mlflow.search_runs()]"]
        volumeMounts:
        - name: model-volume
          mountPath: /app/models
      restartPolicy: Never
      volumes:
      - name: model-volume
        persistentVolumeClaim:
          claimName: titanic-models-pvc
