apiVersion: batch/v1
kind: Job
metadata:
  name: list-files
  namespace: titanic-prediction
spec:
  template:
    spec:
      containers:
      - name: list-files
        image: titanic-prediction:latest
        imagePullPolicy: Never
        command: ["sh", "-c", "ls -la /app/models/"]
        volumeMounts:
        - name: model-volume
          mountPath: /app/models
      restartPolicy: Never
      volumes:
      - name: model-volume
        persistentVolumeClaim:
          claimName: titanic-models-pvc
