apiVersion: batch/v1
kind: Job
metadata:
  name: read-model
  namespace: titanic-prediction
spec:
  template:
    spec:
      containers:
      - name: read-model
        image: titanic-prediction:latest
        imagePullPolicy: Never
        command: ["sh", "-c", "cat /app/models/titanic_model.joblib"]
        volumeMounts:
        - name: model-volume
          mountPath: /app/models
      restartPolicy: Never
      volumes:
      - name: model-volume
        persistentVolumeClaim:
          claimName: titanic-models-pvc
