apiVersion: v1
kind: ConfigMap
metadata:
  name: titanic-prediction-config
  namespace: titanic-prediction
  labels:
    app: titanic-prediction
data:
  # Environment settings
  ENVIRONMENT: "production"
  DEBUG: "false"
  
  # Logging configuration
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"
  
  # MLflow configuration
  MLFLOW_TRACKING_URI: "file:///app/models/mlruns"
  MLFLOW_EXPERIMENT_NAME: "titanic-prediction"
  MLFLOW_MODEL_REGISTRY: "/app/models"
  
  # Model paths and configurations
  MODEL_PATH: "/app/models"
  MODEL_VERSION: "1"
  MODEL_THRESHOLD: "0.5"
  MODEL_FEATURES: "Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Title,FamilySize,IsAlone"
  
  # Feature engineering settings
  FEATURE_ENGINEERING_IMPUTE_AGE: "true"
  FEATURE_ENGINEERING_IMPUTE_FARE: "true"
  FEATURE_ENGINEERING_CREATE_TITLE: "true"
  FEATURE_ENGINEERING_CREATE_FAMILY_SIZE: "true"
  FEATURE_ENGINEERING_CREATE_IS_ALONE: "true"
  
  # API settings
  API_TITLE: "Titanic Survival Prediction API"
  API_DESCRIPTION: "API for predicting survival probability for Titanic passengers"
  API_VERSION: "1.0.0"
  API_PREFIX: "/api/v1"
  MAX_CONNECTIONS: "100"
  WORKERS: "4"
  TIMEOUT: "60"
  ALLOW_ORIGINS: "*"
  RATE_LIMIT: "100"
  RATE_LIMIT_TIMEFRAME: "60"
  
  # Cache and performance optimization settings
  ENABLE_PREDICTION_CACHE: "true"
  CACHE_TTL_SECONDS: "3600"
  BATCH_SIZE_LIMIT: "100"
  MAX_WORKERS: "4"
  ENABLE_RESPONSE_COMPRESSION: "true"
  COMPRESSION_MINIMUM_SIZE: "1000"
  CONNECTION_POOL_MIN_SIZE: "5"
  CONNECTION_POOL_MAX_SIZE: "20"
  MODEL_WARMUP_ENABLED: "true"
  METRICS_ENABLED: "true"
  DETAILED_METRICS: "true"

