apiVersion: v1
kind: Service
metadata:
  name: titanic-prediction-metrics
  namespace: default
  labels:
    app: titanic-prediction
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8000"
spec:
  selector:
    app: titanic-prediction
  ports:
  - name: metrics
    port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP

