apiVersion: v1
kind: PersistentVolume
metadata:
  name: titanic-models-pv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: titanic-models-pvc
  namespace: titanic-prediction
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 