apiVersion: apps/v1
kind: Deployment
metadata:
  name: titanic-prediction
  namespace: titanic-prediction
  labels:
    app: titanic-prediction
spec:
  replicas: 3
  selector:
    matchLabels:
      app: titanic-prediction
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: titanic-prediction
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: titanic-prediction
        image: titanic-prediction:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 9090
          name: metrics
        resources:
          requests:
            cpu: "1000m"
            memory: "1Gi"
          limits:
            cpu: "2000m"
            memory: "2Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 60
          timeoutSeconds: 10
          periodSeconds: 30
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 15
          failureThreshold: 3
        env:
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: titanic-prediction-config
              key: ENVIRONMENT
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              name: titanic-prediction-config
              key: DEBUG
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: titanic-prediction-config
              key: LOG_LEVEL
        - name: MLFLOW_TRACKING_URI
          valueFrom:
            configMapKeyRef:
              name: titanic-prediction-config
              key: MLFLOW_TRACKING_URI
        - name: MLFLOW_EXPERIMENT_NAME
          valueFrom:
            configMapKeyRef:
              name: titanic-prediction-config
              key: MLFLOW_EXPERIMENT_NAME
        - name: MLFLOW_MODEL_REGISTRY
          valueFrom:
            configMapKeyRef:
              name: titanic-prediction-config
              key: MLFLOW_MODEL_REGISTRY
        - name: MODEL_PATH
          valueFrom:
            configMapKeyRef:
              name: titanic-prediction-config
              key: MODEL_PATH
        - name: MODEL_VERSION
          valueFrom:
            configMapKeyRef:
              name: titanic-prediction-config
              key: MODEL_VERSION
        - name: API_PREFIX
          valueFrom:
            configMapKeyRef:
              name: titanic-prediction-config
              key: API_PREFIX
        - name: WORKERS
          valueFrom:
            configMapKeyRef:
              name: titanic-prediction-config
              key: WORKERS
        - name: MAX_WORKERS
          valueFrom:
            configMapKeyRef:
              name: titanic-prediction-config
              key: MAX_WORKERS
        - name: METRICS_ENABLED
          valueFrom:
            configMapKeyRef:
              name: titanic-prediction-config
              key: METRICS_ENABLED
        - name: DETAILED_METRICS
          valueFrom:
            configMapKeyRef:
              name: titanic-prediction-config
              key: DETAILED_METRICS
        volumeMounts:
        - name: model-volume
          mountPath: /app/models
      volumes:
      - name: model-volume
        persistentVolumeClaim:
          claimName: titanic-models-pvc

